// src/components/Common/Footer.vue
<template>
  <p class='text-right container-fluid'>
    Uso apenas para simulação de voo |
    <a href="https://github.com/jpedroh/mach/blob/master/CHANGELOG.md#340---2018-06-26" target="_blank">Mach v3.4.0</a> | Desenvolvido por
    <a href='http://jpedroh.github.io/' target='_blank'>João Pedro Henrique</a>
  </p>
</template>

// modules/web/shared/ui/src/components/layout/footer/index.tsx
import { twc } from 'react-twc'
import { Link } from '../../link'

const Container = twc.div`dark:text-white text-center w-full`

export function Footer() {
  return (
    <Container>
      <p>
        <Link href="https://github.com/jpedroh/mach/" target="_blank">
          Mach
        </Link>
        {' - '}
        Use for flight simulation only
      </p>
      <p>
        Developed by{' '}
        <Link href="https://jpedroh.dev" target="_blank">
          João Pedro Henrique
        </Link>
      </p>
    </Container>
  )
}
